name: Docker

on:
  push:
    branches: [ main ]
env:
  REGISTRY_URL: "${{ REGISTRY_URL }}"
  REGISTRY_USER: "${{ REGISTRY_USER }}"
  REGISTRY_PASSWORD: "${{ REGISTRY_PASS }}"
  MM_NOTIFY_URL: ""

jobs:

  build:
    name: Pull
    runs-on: ubuntu-latest
    steps:
    - name: Setup Docker buildx
      uses: docker/setup-buildx-action@79abd3f86f79a9d68a23c75a09a9a85889262adf

    - name: Check out code
      uses: actions/checkout@v2

    - name: Build and push image to ACR EE
      run: |
        docker login -u $REGISTRY_USER -p $REGISTRY_PASSWORD $REGISTRY
        sh pull.sh
