name: Docker

on:
  push:
    branches: [ main ]
env:
  MY_REGISTRY_URL: "${{ secrets.REGISTRY_URL }}"
  MY_REGISTRY_USER: "${{ secrets.REGISTRY_USER }}"
  MY_REGISTRY_PASSWORD: "${{ secrets.REGISTRY_PASS }}"

jobs:

  build:
    name: Pull
    runs-on: ubuntu-latest
    steps:
    - name: Setup Docker buildx
      uses: docker/setup-buildx-action@79abd3f86f79a9d68a23c75a09a9a85889262adf

    - name: Check out code
      uses: actions/checkout@v2

    - name: Build and push image to ACR EE
      run: |
        docker logout docker.io
        docker logout 
        docker logout $MY_REGISTRY_URL
        docker login -u $MY_REGISTRY_USER -p $MY_REGISTRY_PASSWORD $MY_REGISTRY_URL
        sh pull.sh
