name: Docker

on:
  push:
    branches: [ main ]
env:
  MY_REGISTRY_URL: "${{ secrets.REGISTRY_URL }}"
  MY_REGISTRY_USER: "${{ secrets.REGISTRY_USER }}"
  MY_REGISTRY_PASSWORD: "${{ secrets.REGISTRY_PASS }}"

jobs:

  build:
    name: Pull
    runs-on: ubuntu-latest
    steps:
    - name: Setup Docker buildx
      uses: docker/setup-buildx-action@79abd3f86f79a9d68a23c75a09a9a85889262adf

    - name: Check out code
      uses: actions/checkout@v2

    - name: Build and push image to ACR EE
      run: |
        docker pull alpine:latest
        docker logout docker.io
        docker logout 
        docker logout registry.codefine.site:6870
        docker login -u $MY_REGISTRY_USER -p $MY_REGISTRY_PASSWORD registry.codefine.site:6870
        docker tag alpine:latest registry.codefine.site:6870/shentar/alpine:latest
        docker push registry.codefine.site:6870/shentar/alpine:latest
